export const BLOG_LANG = 'zh'
export const BLOG_URL = 'https://brianyao.tech/'
export const BLOG_ICON = 'https://brianyao.tech/favicon-32x32.png'
export const BLOG_TITLE = `Brian Yao's blog`
export const BLOG_DESCRIPTION = '一个前端开发者的博客，记录 web 开发的一些技术和心得。'
export const BLOG_AUTHOR = 'Brian Yao'
export const BLOG_AUTHOR_ABOUT =
  'Brian Yao 是一个前端开发者，专注于 web 开发，热爱分享。目标是成为一名全栈工程师。'
export const BLOG_AUTHOR_EMAIL = 'chunlai0928@gmail.com'
export const BLOG_AUTHOR_LINK = 'https://brianyao.tech/'
export const BLOG_AUTHOR_AVATAR = 'https://brianyao.tech/images/avatar.jpeg'
export const BLOG_AUTHOR_TWITTER = 'https://twitter.com/yclgkd'
export const BLOG_AUTHOR_TWITTER_USERNAME = '@yclgkd'
export const BLOG_AUTHOR_GITHUB = 'https://github.com/yclkgd'
export const BLOG_AUTHOR_CODEPEN = 'https://codepen.io/yclgkd'
